# Timeout in seconds that Limine will use before automatically booting.
timeout: 5

# The entry name that will be displayed in the boot menu.
/valern-x86_64
    protocol: limine

    path: boot():/boot/valern-x86_64